[2019-11-03 11:07:48,940] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Stage_stars 2018-11-03T01:00:00+00:00 [queued]>
[2019-11-03 11:07:48,944] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Stage_stars 2018-11-03T01:00:00+00:00 [queued]>
[2019-11-03 11:07:48,944] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-11-03 11:07:48,944] {taskinstance.py:839} INFO - Starting attempt 4 of 4
[2019-11-03 11:07:48,944] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-11-03 11:07:48,949] {taskinstance.py:859} INFO - Executing <Task(StageToRedshiftOperator): Stage_stars> on 2018-11-03T01:00:00+00:00
[2019-11-03 11:07:48,950] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_dag', 'Stage_stars', '2018-11-03T01:00:00+00:00', '--job_id', '39', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/capstone_dag.py', '--cfg_path', '/var/folders/8q/nyxhvd6d55nfqjdbrybk6jpw0000gn/T/tmpaskmi5sk']
[2019-11-03 11:07:49,703] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars /Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2019-11-03 11:07:49,704] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars   """)
[2019-11-03 11:07:49,792] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars [2019-11-03 11:07:49,791] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-11-03 11:07:50,142] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars [2019-11-03 11:07:50,141] {dagbag.py:90} INFO - Filling up the DagBag from /Users/likejun/airflow/dags/capstone_dag.py
[2019-11-03 11:07:50,155] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars [2019-11-03 11:07:50,155] {cli.py:516} INFO - Running <TaskInstance: capstone_dag.Stage_stars 2018-11-03T01:00:00+00:00 [running]> on host likejundeMacBook-Pro.local
[2019-11-03 11:07:50,161] {staging_redshift.py:33} INFO - StageToRedshiftOperator for staging_stars on 2018-11-03T01:00:00+00:00
[2019-11-03 11:07:50,168] {staging_redshift.py:44} INFO - copy command 
        COPY staging_stars FROM 's3://dend-capstone-lkj/star.json'
        ACCESS_KEY_ID 'AKIA2ZJJD7TPQUMASLMS'
        SECRET_ACCESS_KEY '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'
        REGION 'us-west-2'
        JSON 'auto';
        
[2019-11-03 11:07:50,170] {logging_mixin.py:95} INFO - [[34m2019-11-03 11:07:50,170[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-03 11:09:05,761] {taskinstance.py:1051} ERROR - could not connect to server: Operation timed out
	Is the server running on host "redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com" (44.225.40.86) and accepting
	TCP/IP connections on port 5439?
Traceback (most recent call last):
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/likejun/airflow/plugins/operators/staging_redshift.py", line 47, in execute
    pg_hook.run(copy_stmt)
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
    with closing(self.get_conn()) as conn:
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/postgres_hook.py", line 75, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Operation timed out
	Is the server running on host "redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com" (44.225.40.86) and accepting
	TCP/IP connections on port 5439?

[2019-11-03 11:09:05,765] {taskinstance.py:1080} INFO - All retries failed; marking task as FAILED
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars Traceback (most recent call last):
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars   File "/Users/likejun/anaconda3/bin/airflow", line 32, in <module>
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars     args.func(args)
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars     return f(*args, **kwargs)
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars     _run(args, dag, ti)
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars     pool=args.pool,
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars     return func(*args, **kwargs)
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars     result = task_copy.execute(context=context)
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars   File "/Users/likejun/airflow/plugins/operators/staging_redshift.py", line 47, in execute
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars     pg_hook.run(copy_stmt)
[2019-11-03 11:09:05,779] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
[2019-11-03 11:09:05,780] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars     with closing(self.get_conn()) as conn:
[2019-11-03 11:09:05,780] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/postgres_hook.py", line 75, in get_conn
[2019-11-03 11:09:05,780] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars     self.conn = psycopg2.connect(**conn_args)
[2019-11-03 11:09:05,780] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
[2019-11-03 11:09:05,780] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2019-11-03 11:09:05,780] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars psycopg2.OperationalError: could not connect to server: Operation timed out
[2019-11-03 11:09:05,780] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars 	Is the server running on host "redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com" (44.225.40.86) and accepting
[2019-11-03 11:09:05,780] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars 	TCP/IP connections on port 5439?
[2019-11-03 11:09:05,780] {base_task_runner.py:115} INFO - Job 39: Subtask Stage_stars 
[2019-11-03 11:09:09,029] {logging_mixin.py:95} INFO - [[34m2019-11-03 11:09:09,029[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
