[2019-11-17 14:10:13,317] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: dend_dag.Load_repositories_fact_table 2018-11-03T00:00:00+00:00 [queued]>
[2019-11-17 14:10:13,322] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: dend_dag.Load_repositories_fact_table 2018-11-03T00:00:00+00:00 [queued]>
[2019-11-17 14:10:13,322] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-11-17 14:10:13,322] {taskinstance.py:839} INFO - Starting attempt 4 of 4
[2019-11-17 14:10:13,322] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-11-17 14:10:13,327] {taskinstance.py:859} INFO - Executing <Task(LoadFactOperator): Load_repositories_fact_table> on 2018-11-03T00:00:00+00:00
[2019-11-17 14:10:13,327] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'dend_dag', 'Load_repositories_fact_table', '2018-11-03T00:00:00+00:00', '--job_id', '232', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dend_dag.py', '--cfg_path', '/var/folders/8q/nyxhvd6d55nfqjdbrybk6jpw0000gn/T/tmpgouf8tob']
[2019-11-17 14:10:14,107] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table /Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2019-11-17 14:10:14,107] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table   """)
[2019-11-17 14:10:14,189] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table [2019-11-17 14:10:14,188] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-11-17 14:10:14,474] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table [2019-11-17 14:10:14,474] {dagbag.py:90} INFO - Filling up the DagBag from /Users/likejun/airflow/dags/dend_dag.py
[2019-11-17 14:10:14,490] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table [2019-11-17 14:10:14,490] {cli.py:516} INFO - Running <TaskInstance: dend_dag.Load_repositories_fact_table 2018-11-03T00:00:00+00:00 [running]> on host likejundeMacBook-Pro.local
[2019-11-17 14:10:14,498] {load_facts.py:21} INFO - LoadFactOperator for repository_fact
[2019-11-17 14:10:14,507] {logging_mixin.py:95} INFO - [[34m2019-11-17 14:10:14,507[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 14:14:20,158] {taskinstance.py:1051} ERROR - could not receive data from server: Operation timed out
Traceback (most recent call last):
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/likejun/airflow/plugins/operators/load_facts.py", line 30, in execute
    pg_hook.run(SqlQueries.repository_table_select)
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
    with closing(self.get_conn()) as conn:
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/postgres_hook.py", line 75, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.DatabaseError: could not receive data from server: Operation timed out

[2019-11-17 14:14:20,160] {taskinstance.py:1080} INFO - All retries failed; marking task as FAILED
[2019-11-17 14:14:20,174] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table Traceback (most recent call last):
[2019-11-17 14:14:20,175] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/bin/airflow", line 32, in <module>
[2019-11-17 14:14:20,175] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table     args.func(args)
[2019-11-17 14:14:20,175] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-11-17 14:14:20,175] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table     return f(*args, **kwargs)
[2019-11-17 14:14:20,175] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-11-17 14:14:20,175] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table     _run(args, dag, ti)
[2019-11-17 14:14:20,175] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-11-17 14:14:20,176] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table     pool=args.pool,
[2019-11-17 14:14:20,176] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-11-17 14:14:20,176] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table     return func(*args, **kwargs)
[2019-11-17 14:14:20,176] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-11-17 14:14:20,176] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table     result = task_copy.execute(context=context)
[2019-11-17 14:14:20,176] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table   File "/Users/likejun/airflow/plugins/operators/load_facts.py", line 30, in execute
[2019-11-17 14:14:20,176] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table     pg_hook.run(SqlQueries.repository_table_select)
[2019-11-17 14:14:20,176] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
[2019-11-17 14:14:20,176] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table     with closing(self.get_conn()) as conn:
[2019-11-17 14:14:20,176] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/hooks/postgres_hook.py", line 75, in get_conn
[2019-11-17 14:14:20,177] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table     self.conn = psycopg2.connect(**conn_args)
[2019-11-17 14:14:20,177] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
[2019-11-17 14:14:20,177] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2019-11-17 14:14:20,177] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table psycopg2.DatabaseError: could not receive data from server: Operation timed out
[2019-11-17 14:14:20,177] {base_task_runner.py:115} INFO - Job 232: Subtask Load_repositories_fact_table 
[2019-11-17 14:14:23,618] {logging_mixin.py:95} INFO - [[34m2019-11-17 14:14:23,617[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
