[2019-11-16 10:45:01,085] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Load_repositories_fact_table 2018-11-03T16:00:00+00:00 [queued]>
[2019-11-16 10:45:01,089] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Load_repositories_fact_table 2018-11-03T16:00:00+00:00 [queued]>
[2019-11-16 10:45:01,090] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-11-16 10:45:01,090] {taskinstance.py:839} INFO - Starting attempt 2 of 4
[2019-11-16 10:45:01,090] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-11-16 10:45:01,094] {taskinstance.py:859} INFO - Executing <Task(LoadFactOperator): Load_repositories_fact_table> on 2018-11-03T16:00:00+00:00
[2019-11-16 10:45:01,094] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_dag', 'Load_repositories_fact_table', '2018-11-03T16:00:00+00:00', '--job_id', '193', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/capstone_dag.py', '--cfg_path', '/var/folders/8q/nyxhvd6d55nfqjdbrybk6jpw0000gn/T/tmp4szvhyc7']
[2019-11-16 10:45:01,775] {base_task_runner.py:115} INFO - Job 193: Subtask Load_repositories_fact_table /Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2019-11-16 10:45:01,775] {base_task_runner.py:115} INFO - Job 193: Subtask Load_repositories_fact_table   """)
[2019-11-16 10:45:01,853] {base_task_runner.py:115} INFO - Job 193: Subtask Load_repositories_fact_table [2019-11-16 10:45:01,852] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-11-16 10:45:02,129] {base_task_runner.py:115} INFO - Job 193: Subtask Load_repositories_fact_table [2019-11-16 10:45:02,128] {dagbag.py:90} INFO - Filling up the DagBag from /Users/likejun/airflow/dags/capstone_dag.py
[2019-11-16 10:45:02,141] {base_task_runner.py:115} INFO - Job 193: Subtask Load_repositories_fact_table [2019-11-16 10:45:02,141] {cli.py:516} INFO - Running <TaskInstance: capstone_dag.Load_repositories_fact_table 2018-11-03T16:00:00+00:00 [running]> on host likejundeMacBook-Pro.local
[2019-11-16 10:45:02,147] {load_facts.py:21} INFO - LoadFactOperator for repositories
[2019-11-16 10:45:02,152] {logging_mixin.py:95} INFO - [[34m2019-11-16 10:45:02,151[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-16 11:27:44,420] {logging_mixin.py:95} INFO - [[34m2019-11-16 11:27:44,419[0m] {[34mlocal_task_job.py:[0m158} [33mWARNING[0m - [33mThe recorded hostname [1mlikejundeMacBook-Pro.local[0m does not match this instance's hostname [1m1.0.0.127.in-addr.arpa[0m[0m
[2019-11-16 11:27:44,428] {helpers.py:307} INFO - Sending Signals.SIGTERM to GPID 14304
[2019-11-16 11:28:44,445] {helpers.py:319} WARNING - process psutil.Process(pid=14304, name='python3.7', started='10:45:01') (14304) did not respond to SIGTERM. Trying SIGKILL
[2019-11-16 11:28:45,792] {helpers.py:285} INFO - Process psutil.Process(pid=14304, status='terminated') (14304) terminated with exit code -9
