[2019-11-16 12:00:22,599] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Load_repositories_fact_table 2018-11-03T16:00:00+00:00 [queued]>
[2019-11-16 12:00:22,603] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_dag.Load_repositories_fact_table 2018-11-03T16:00:00+00:00 [queued]>
[2019-11-16 12:00:22,603] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-11-16 12:00:22,603] {taskinstance.py:839} INFO - Starting attempt 3 of 4
[2019-11-16 12:00:22,604] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-11-16 12:00:22,608] {taskinstance.py:859} INFO - Executing <Task(LoadFactOperator): Load_repositories_fact_table> on 2018-11-03T16:00:00+00:00
[2019-11-16 12:00:22,608] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_dag', 'Load_repositories_fact_table', '2018-11-03T16:00:00+00:00', '--job_id', '194', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/capstone_dag.py', '--cfg_path', '/var/folders/8q/nyxhvd6d55nfqjdbrybk6jpw0000gn/T/tmpxs4mz2x1']
[2019-11-16 12:00:23,275] {base_task_runner.py:115} INFO - Job 194: Subtask Load_repositories_fact_table /Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2019-11-16 12:00:23,276] {base_task_runner.py:115} INFO - Job 194: Subtask Load_repositories_fact_table   """)
[2019-11-16 12:00:23,354] {base_task_runner.py:115} INFO - Job 194: Subtask Load_repositories_fact_table [2019-11-16 12:00:23,354] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-11-16 12:00:23,624] {base_task_runner.py:115} INFO - Job 194: Subtask Load_repositories_fact_table [2019-11-16 12:00:23,624] {dagbag.py:90} INFO - Filling up the DagBag from /Users/likejun/airflow/dags/capstone_dag.py
[2019-11-16 12:00:23,636] {base_task_runner.py:115} INFO - Job 194: Subtask Load_repositories_fact_table [2019-11-16 12:00:23,636] {cli.py:516} INFO - Running <TaskInstance: capstone_dag.Load_repositories_fact_table 2018-11-03T16:00:00+00:00 [running]> on host likejundeMacBook-Pro.local
[2019-11-16 12:00:23,642] {load_facts.py:21} INFO - LoadFactOperator for repositories
[2019-11-16 12:00:23,649] {logging_mixin.py:95} INFO - [[34m2019-11-16 12:00:23,649[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-16 13:13:48,214] {logging_mixin.py:95} INFO - [[34m2019-11-16 13:13:48,213[0m] {[34mlocal_task_job.py:[0m158} [33mWARNING[0m - [33mThe recorded hostname [1mlikejundeMacBook-Pro.local[0m does not match this instance's hostname [1m1.0.0.127.in-addr.arpa[0m[0m
[2019-11-16 13:13:48,219] {helpers.py:307} INFO - Sending Signals.SIGTERM to GPID 15078
[2019-11-16 13:14:48,189] {helpers.py:319} WARNING - process psutil.Process(pid=15078, name='python3.7', started='12:00:22') (15078) did not respond to SIGTERM. Trying SIGKILL
[2019-11-16 13:14:49,851] {helpers.py:285} INFO - Process psutil.Process(pid=15078, status='terminated') (15078) terminated with exit code -9
